sudo: required

services:
  - docker

env:
  matrix:
    - SOFTWARE="BU" VERSION="1.5.0.0"

before_script:
  - docker version

script:
  - docker build -f ./${SOFTWARE}/${VERSION}/Dockerfile -t ${SOFTWARE}-${VERSION} ./${SOFTWARE}/${VERSION}

after_script:
  - docker images
